todoism/blueprints/auth.py
import random
from datetime import datetime

from faker import Faker
from flask import render_template, jsonify, redirect, url_for, request, flash
from flask_login import login_required, login_user, logout_user, current_user
from flask.blueprints import Blueprint

from todoism.email import send_confirm_mail
from todoism.models import User, Item
from todoism.extensions import db
from todoism.utils import generate_token, validate_token

auth_bp = Blueprint('auth', __name__)
faker = Faker()


@auth_bp.route('/get_test_account')
def get_test_account():
    email = faker.email()
    while User.query.filter_by(name=email).first() is not None:
        email = faker.email()
    fake_name = faker.user_name()
    password = faker.word()
    user=User(name=fake_name, email=email, confirmed=True)
    user.set_password(password)

    db.session.add(user)

    todo_contents = [
        'Witness something truly majestic',
        'Help a complete stranger',
        'Drive a motorcycle on the Great Wall of China',
        'Sit on the Great Egyptian Pyramids',
        '找个好工作',
        '买个苹果AirPods Pro',
        '注册功能完善（电子邮件，token验证）',
        '优先级,设置，修改。。。',
        '拖拽调整顺序。。',
        '设定deadline并提醒',
        '倒垃圾',
        '国际化',
    ]
    items = []
    for i, content in enumerate(todo_contents):
        item = Item(content=content, author=user, priority=random.randrange(1,4,1))
        if i in [1, 6, 7, 10]:
            item.done = True
            item.done_time = datetime.utcnow()
        items.append(item)

    db.session.add_all(items)
    db.session.commit()
    return jsonify(email=email, password=password, message='假账号生成成功')


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('todo.app'))
    if request.method == 'POST':
        data = request.get_json()
        email = data['email']
        username = data['username']
        password = data['password']
        if User.query.filter_by(email=email.lower()).first():
            return jsonify(message='该邮箱已注册！', code='e101')
        user = User(name=username, email=email.lower())
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        token = generate_token(user=user, operation='confirm')
        send_confirm_mail(user, token)
        return jsonify(message='注册成功，请验登录后验证邮箱')
    return render_template('_register.html')


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    # if not current_user.is_authenticated:
    #     flash('请先登录！','warning')
    #     next = request.url
    #     return redirect(url_for('home.index') + '#login&next=' + next, code=302)
    if current_user.confirmed:
        flash('已确认，无需操作')
        return redirect(url_for('home.index') + '#app')
    if validate_token(user=current_user, token=token, operation='confirm'):
        flash('确认成功！')
        return redirect(url_for('home.index') + '#app')
    else:
        flash('令牌过期或有误，请重新发送确认邮件！')
        return redirect(url_for('home.index') + '#app')


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('todo.app'))
    if request.method == 'POST':
        data = request.get_json()
        email = data['email']
        password = data['password']

        user = User.query.filter_by(email=email).first()
        if user and user.valid_password(password):
            login_user(user)
            message = '登陆成功'
            if not user.confirmed:
                message += ',请验证邮箱'
            return jsonify(message=message)
        else:
            return jsonify(message='用户或密码错误'), 400
    return render_template('_login.html')




@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return jsonify(message='您已登出！')

todoism/blueprints/home.py
from flask import render_template
from flask.blueprints import Blueprint

home_bp = Blueprint('home', __name__)


@home_bp.route('/')
def index():
    return render_template('index.html')


@home_bp.route('/intro')
def intro():
    return render_template('_intro.html')

todoism/templates/_app.html
{% extends 'base.html' %}

{% block content %}
    <header class="row">
        <input id="item-input" data-href="{{ url_for('.new_item') }}" type="text"
               placeholder="您想干点啥（需要国际化）" autocomplete="off" autofocus required>
    </header>

    <div class="row" id="dashboard">
        <div class="col l9 s12 m12">
            <ul class="tabs">
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="all-item">
                        全部 <span class="grey-text small-text" id="all-count">{{ all_count }}</span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="active-item">
                        现存 <span class="grey-text small-text" id="active-count">{{ active_count }}</span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="completed-item">
                        已干 <span class="grey-text small-text" id="completed-count">{{ completed_count }}</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col l3 hide-on-med-and-down">
            <a class="waves-effect waves-light btn red right" id="clear-btn" data-href="{{ url_for('.clear') }}"
               title="清除已完成事项">
                <i class="material-icons left">clear_all</i>Clear
            </a>
        </div>
    </div>

    <div class="items">
        {% for item in items %}
            {% include '_item.html' %}
        {% endfor %}
    </div>
{% endblock %}

todoism/templates/_intro.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <h2 class="teal-text text-lighten-2">Todoism</h2>
        <h5 class="light">{{ 'We are todoist, we use todoism.' }}</h5>
        <div class="row center-block">
            <div class="fake-browser-ui hoverable card-panel">
                <div class="frame">
                    <span class="red"></span>
                    <span class="blue"></span>
                    <span class="orange"></span>
                </div>
                <img class="responsive-img" src="{{ url_for('static', filename='demo.png') }}">
            </div>
        </div>
        <div class="row">
            <a href="#login" class="btn waves-effect waves-light red">{{ 'Get Started' }}</a>
        </div>
    </div>
{% endblock %}

todoism/templates/_item.html
<div class="row item card-panel hoverable" data-href="{{ url_for('.edit_item', item_id=item.id) }}"
     data-id="{{ item.id }}" data-body="{{ item.body }}" data-done={{ item.done|tojson }} data-priority="{{ item.priority }}">
    <span class="item-body">
        <a class="button done-btn" data-href="{{ url_for('.toggle_item', item_id=item.id) }}">
            <i class="material-icons left">{% if item.done %}check_box{% else %}check_box_outline_blank{% endif %}</i>
        </a>
        <span class="{% if item.done %}inactive-item{% else %}active-item{% endif %}"
              id="body{{ item.id }}">{{ item.content }}</span>
        <a title="点击以修改优先级" class="dropdown-trigger label {% if item.priority == 1 %}label-normal{% elif item.priority == 2 %}label-important{% else %}label-emergency{% endif %} round"
             data-target="priority-dropdown-{{ item.id }}"></a>
        <div id='priority-dropdown-{{ item.id }}' class='dropdown-content' data-href="{{ url_for('.change_priority', item_id=item.id) }}">
            <a class="label label-normal round" data-priority="1"></a>
            <a class="label label-important round" data-priority="2"></a>
            <a class="label label-emergency round" data-priority="3"></a>
        </div>
        <div class="timeshit">
            <small class="create-time tooltipped" data-position="bottom"
                   data-timestamp="{{ item.create_time.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
    {#            {{ moment(item.create_time).format('YYYY MMMM Do, h:mm:ss a') }}#}
                创建于{{ moment(item.create_time).fromNow(refresh=True) }}
            </small>
            {% if item.done_time %}
                <small class="done-time tooltipped" data-position="bottom"
                       data-timestamp="{{ item.done_time.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
        {#            {{ moment(item.create_time).format('YYYY MMMM Do, h:mm:ss a') }}#}
                    完成于{{ moment(item.done_time).fromNow(refresh=True) }}
                </small>
            {% endif %}
        </div>
    </span>
    <span class="hide edit-btns right">
        <a class="right button delete-btn" data-href="{{ url_for('.delete_item', item_id=item.id) }}">
            <i class="material-icons small-icon left">clear</i>
        </a>
        <a class="right button edit-btn">
            <i class="material-icons small-icon left">mode_edit</i>
        </a>
    </span>
</div>

todoism/templates/_login.html
{% extends 'base.html' %}

{% block content %}
    <header class="center">
        <h4 class="red-text">Login on Todoism</h4><br>
    </header>
    <div class="login-form">
        <input class="validate login-input" id="username-input" name="username" type="text" placeholder="Username"
               autofocus required>
        <input class="validate login-input" id="password-input" name="password" type="password" placeholder="Password"
               required>
        <span class="right">
            <a class="btn grey" id="register-btn">Get a test account</a>
            <a class="btn red" id="login-btn">Login</a>
        </span>
        <p><a class="blue-text link button left" id="toggle-password">Toggle Password</a></p>&nbsp;
    </div>
{% endblock %}

todoism/templates/_register.html
{% extends 'base.html' %}

{% block content %}
    <header class="center">
        <h4 class="red-text">Sign up Todoism</h4><br>
    </header>
    <div class="login-form">
        <input class="validate login-input" id="email-input" name="email" type="text" placeholder="Email"
               autofocus required>
        <input class="validate login-input" id="username-input" name="username" type="text" placeholder="Username"
               required>
        <input class="validate login-input" id="password-input" name="password" type="password" placeholder="Password"
               required>
        <input class="validate login-input" id="password-input2" name="password2" type="password" placeholder="Confirm Password"
               required>
        <span class="right">
            <a class="btn blue" id="register-btn">Register</a>
        </span>
        <p><a class="blue-text link button left" id="toggle-password">Toggle Password</a></p>&nbsp;
    </div>
{% endblock %}

todoism/templates/base.html
<nav class="green lighten-2" role="navigation">
    <div class="nav-wrapper container">
        <a href="#intro" class="brand-logo">Todoism</a>
        <a data-target="nav-mobile" class="sidenav-trigger button"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            {% if current_user.is_authenticated %}
                <li>
                    <a class="waves-effect waves-light btn orange" href="#app">{{ current_user.name }}
                        <span class="badge new" id="active-count-nav">{{ active_items }}</span>
                    </a>
                </li>
                <li>
                    <a class="waves-effect waves-light" id="logout-btn" data-href="{{ url_for('auth.logout') }}" title="登出">
                        <i class="material-icons">power_settings_new</i>
                    </a>
                </li>
            {% else %}
                <li><a class="waves-effect waves-light btn red" href="#login">Login</a></li>
                <li><a class="waves-effect waves-light btn red" href="#register">Register</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<ul id="nav-mobile" class="sidenav">
    {% if current_user.is_authenticated %}
        <li><a class="waves-effect waves-light btn red clear-btn sidenav-close">Clear</a></li>
        <li><a class="waves-effect waves-light btn orange sidenav-close" id="app-btn"
               href="#app">{{ current_user.name }}</a>
        </li>
        <li><a class="waves-effect waves-light btn grey sidenav-close" id="logout-btn"
               data-href="{{ url_for('auth.logout') }}">Logout</a></li>
    {% else %}
        <li><a class="waves-effect waves-light btn red sidenav-close" href="#login">Login</a></li>
        <li><a class="waves-effect waves-light btn red sidenav-close" href="#register">Register</a></li>
    {% endif %}
</ul>

{% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
{% endfor %}
<main>
    {% block content %}{% endblock %}
</main>
<footer class="center">
    <small> &copy; 2020 <a class="blue-text link" href="https://github.com/zyitst" title="Written by zyitst">Zyitst</a> -
        <a class="blue-text link" href="https://github.com/zyitst/todosim2" title="Fork me on GitHub">GitHub</a> -
        <a class="blue-text link" href="http://greyli.com" title="特别感谢:李辉">鸣谢</a>
    </small>
</footer>

todoism/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Todoism</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<div id="main"></div>
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";
    var login_page_url = "{{ url_for('auth.login') }}";
    var login_url = "{{ url_for('auth.login') }}";
    var register_page_url = "{{ url_for('auth.register') }}";
    var test_account_url = "{{ url_for('auth.get_test_account') }}";
    var logout_url = "{{ url_for('auth.logout') }}";
    {#var default_error_message = "Oops, something was wrong!";#}
    var default_error_message = "完蛋，出毛病了！";
    var empty_body_error_message = "Your todo was empty!";
    var register_error_message = "注册信息错误，请检查！";
    var login_error_message = "Empty username or password!";
    var app_page_url = "{{ url_for('todo.app') }}";
    var intro_page_url = "{{ url_for('home.intro') }}";
</script>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
{#    {{ moment.include_jquery() }}#}
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale(auto_detect=True) }}
    <script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
</body>
</html>